connection_mode=mmapper
connection_host=localhost
connection_port=4242
show_status=1
show_buffs=1
show_group=1
show_comm=1
show_ui=1
show_dev=0
show_pane_dividers=1
pane_color_status=black
pane_color_buffs=red
pane_color_group=green
pane_color_comm=blue
pane_color_ui=black
pane_color_dev=grey
profile=default
spotlights_show_deaths=1
spotlights_show_levelups=1
spotlights_show_pvp=1
spotlights_show_achievements=1
terminal_bg_fallback=#000000
