return {
    spells = {
        ["magic missile"]       = { shortest = "magic m"  },
        ["ventriloquate"]       = { shortest = "v"        },
        ["detect invisibility"] = { shortest = "detect i" },
        ["detect magic"]        = { shortest = "detect m" },
        ["armour"]              = { shortest = "a"        },
        ["chill touch"]         = { shortest = "chi"      },
        ["create light"]        = { shortest = "cr"       },
        ["locate magic"]        = { shortest = "locate m" },
        ["burning hands"]       = { shortest = "bu"       },
        ["shroud"]              = { shortest = "shr"      },
        ["find the path"]       = { shortest = "fin"      },
        ["locate"]              = { shortest = "locate"   },
        ["call familiar"]       = { shortest = "call f"   },
        ["night vision"]        = { shortest = "n"        },
        ["shocking grasp"]      = { shortest = "sho"      },
        ["earthquake"]          = { shortest = "ea"       },
        ["teleport"]            = { shortest = "t"        },
        ["block door"]          = { shortest = "bl"       },
        ["lightning bolt"]      = { shortest = "li"       },
        ["control weather"]     = { shortest = "con"      },
        ["store"]               = { shortest = "st"       },
        ["colour spray"]        = { shortest = "col"      },
        ["locate life"]         = { shortest = "locate l" },
        ["call lightning"]      = { shortest = "call l"   },
        ["enchant"]             = { shortest = "en"       },
        ["scry"]                = { shortest = "sc"       },
        ["shield"]              = { shortest = "shi"      },
        ["charm"]               = { shortest = "cha"      },
        ["sleep"]               = { shortest = "sl"       },
        ["fireball"]            = { shortest = "fir"      },
        ["dispel magic"]        = { shortest = "di"       },
        ["magic blast"]         = { shortest = "magic b"  },
        ["watch room"]          = { shortest = "w"        },
        ["silence"]             = { shortest = "si"       },
        ["identify"]            = { shortest = "i"        },
        ["portal"]              = { shortest = "p"        },
    }
}
