return {
    spells = {
        ["magic missile"]       = { shortest = "magic m"  },
        ["ventriloquate"]       = { shortest = "ventr"    },
        ["detect invisibility"] = { shortest = "detect i" },
        ["detect magic"]        = { shortest = "detect m" },
        ["armour"]              = { shortest = "armou"    },
        ["chill touch"]         = { shortest = "chill"    },
        ["create light"]        = { shortest = "creat"    },
        ["locate magic"]        = { shortest = "locate m" },
        ["burning hands"]       = { shortest = "burni"    },
        ["shroud"]              = { shortest = "shrou"    },
        ["find the path"]       = { shortest = "find "    },
        ["locate"]              = { shortest = "locate"   },
        ["call familiar"]       = { shortest = "call f"   },
        ["night vision"]        = { shortest = "night"    },
        ["shocking grasp"]      = { shortest = "shock"    },
        ["earthquake"]          = { shortest = "earth"    },
        ["teleport"]            = { shortest = "telep"    },
        ["block door"]          = { shortest = "block"    },
        ["lightning bolt"]      = { shortest = "light"    },
        ["control weather"]     = { shortest = "contr"    },
        ["store"]               = { shortest = "store"    },
        ["colour spray"]        = { shortest = "colou"    },
        ["locate life"]         = { shortest = "locate l" },
        ["call lightning"]      = { shortest = "call l"   },
        ["enchant"]             = { shortest = "encha"    },
        ["scry"]                = { shortest = "scry"     },
        ["shield"]              = { shortest = "shiel"    },
        ["charm"]               = { shortest = "charm"    },
        ["sleep"]               = { shortest = "sleep"    },
        ["fireball"]            = { shortest = "fireb"    },
        ["dispel magic"]        = { shortest = "dispe"    },
        ["magic blast"]         = { shortest = "magic b"  },
        ["watch room"]          = { shortest = "watch"    },
        ["silence"]             = { shortest = "silen"    },
        ["identify"]            = { shortest = "ident"    },
        ["portal"]              = { shortest = "porta"    },
    }
}
